#!/bin/bash
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
#domain=$(cat /etc/xray/domain)
#RAM=$(free -m | awk 'NR==2 {print $2}')
#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')

#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"

clear
# // Gettings Info
function updat(){
clear
cd /usr/local/
rm -rf sbin
rm -rf /usr/bin/enc
cd
mkdir /usr/local/sbin
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m# "
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
res1() {
    wget https://raw.githubusercontent.com/scriswan/v1/Cdy/main/LT
    wget -q -O /usr/bin/enc "https://raw.githubusercontent.com/scriswan/v1/main/Enc/encrypt" ; chmod +x /usr/bin/enc
    7z e -paskykenza123 LT
    unzip LT
    chmod +x menu/*
    enc menu/*
    mv menu/* /usr/local/sbin
    rm -rf menu
    rm -rf LT
    rm -rf update.sh
    rm -rf uodate
    rm -rf /root/menu
    rm -rf /root/menu.zip
    rm -rf /root/update.sh
    rm -rf /root/welcome
    rm -rf /root/change-limit-xray
    rm -rf /root/change-ip-limit
    rm -rf /root/change-domain
    rm -rf /root/fixhap
    rm -rf /root/fixcert
    rm -rf /root/xtra-menu
    rm -rf /root/others
    rm -rf /root/manager
    rm -rf /root/m-ftr
    rm -rf /root/m-bkp
    rm -rf /root/m-bot
    rm -rf /root/m-ssh
    rm -rf /root/m-ssr
    rm -rf /root/m-vme
    rm -rf /root/m-vle
    rm -rf /root/m-tro
    rm -rf /root/mbot
    rm -rf /root/m-panel
    rm -rf /root/add-bot-notif
    rm -rf /root/add-ip
    rm -rf /root/add-ssh
    rm -rf /root/add-vme
    rm -rf /root/add-vle
    rm -rf /root/add-ssr    
    rm -rf /root/auto-kill
    rm -rf /root/autobackup
    rm -rf /root/autoreboot
    rm -rf /root/clearcache
    rm -rf /root/clearlog
    rm -rf /root/backup
    rm -rf /root/restore
    rm -rf /root/cek-ssh
    rm -rf /root/cek-ssr
    rm -rf /root/cek-vle
    rm -rf /root/cek-vme
    rm -rf /root/cek-tro
    rm -rf /root/member-ssh
    rm -rf /root/member-vme
    rm -rf /root/member-vle
    rm -rf /root/member-tro
    rm -rf /root/membee-ssr
    rm -rf /root/user-ssh
    rm -rf /root/user-ssr
    rm -rf /root/user-vme
    rm -rf /root/user-vle
    rm -rf /root/user-tro
    rm -rf /root/renew-ssh
    rm -rf /root/renew-ssr
    rm -rf /root/renew-vme
    rm -rf /root/renew-vle
    rm -rf /root/renew-tro
    rm -rf /root/trial-ssh
    rm -rf /root/trial-vle
    rm -rf /root/trial-ssr
    rm -rf /root/trial-vme
    rm -rf /root/trial-tro
    rm -rf /root/delexp
    rm -rf /root/xp
    rm -rf /root/member
    rm -rf /root/tendang
    rm -rf /root/speedtest
    rm -rf /root/run
    rm -rf /root/reset
    rm -rf /root/gotop
    rm -rf /root/prot
    rm -rf /root/mullog
    rm -rf /root/Lt-on-off
    rm -rf /root/limitspeed
    rm -rf /root/limitssh-ip
    rm -rf /root/lock-vmess
    rm -rf /root/lock-xray-ip
    rm -rf /root/lock
    rm -rf /root/unlock
    rm -rf /root/ganti-ip-ssh
    rm -rf /root/ganti-ip-vmess
    rm -rf /root/ganti-ip-vless
    rm -rf /root/ganti-ip-trojan
    rm -rf /root/del-ssh
    rm -rf /root/del-vme
    rm -rf /root/del-vle
    rm -rf /root/del-ssr
    rm -rf /root/del-tro
    rm -rf /root/create-bot-notif
    rm -rf /root/hapus-bot-notif
    rm -rf /root/ceklim
    rm -rf /root/about
    rm -rf /root/limit-on-off
    rm -rf /root/killtrial
    rm -rf /root/hapus-bot
    rm -rf /root/delet-cache-file
    rm -rf /root/del-bot-notif
    rm -rf /root/change-vmess-qouta
    rm -rf /root/change-vless-qouta
    rm -rf /root/change-trojan-qouta
    rm -rf /root/cf
    rm -rf /root/bot
    rm -rf /root/add-tro
    rm -rf /root/add-ip-bot
    rm -rf /root/about
    rm -rf /root/UDEPE
    rm -rf /root/Bot-Domain
    rm -rf /root/menu-noobzvpns
    rm -rf /root/welcome.bak
    rm -rf /root/scdomain
    rm -rf /root/menu-tai
    rm -rf /root/menu-mentahan
    rm -rf /root/Neo
    rm -rf /root/m-xray
    rm -rf /root/menu.bak
    rm -rf /root/del-bot-notif
    rm -rf /root/delet-cache-file
    rm -rf /root/bot
    rm -rf /root/backup
    rm -rf /root/auto-kill
    rm -rf /root/autoreboot
    rm -rf /root/auto-backup
    rm -rf /root/add-ip-bot
    rm -rf /root/ipbot
    rm -rf /root/cf
    rm -rf /root/change-trojan-qouta
    rm -rf /root/clearcache
    rm -rf /root/clearlog
    rm -rf /root/del-bot-notif
    rm -rf /root/gz13051
    rm -rf /root/gz22349
    rm -rf /root/izinsc
    rm -rf /root/Lt-on-off
    rm -rf /root/udp
    rm -rf /root/user-ssh
    rm -rf /root/user-ssr
    rm -rf /root/user-tro
    rm -rf /root/user-vme
    rm -rf /root/user-vle
}
netfilter-persistent
clear
echo -e "\033[96;1m┌───────────────────────────────────────────┐\033[0m "
echo -e " \e[1;97;101m               UPDATE SCRIPT         \e[0m"
echo -e "\033[96;1m└───────────────────────────────────────────┘\033[0m "
echo -e ""
echo -e "  \033[1;91m Ipdate version Script\033[1;37m"
fun_bar 'res1'
echo -e "\033[96;1m└───────────────────────────────────────────┘\033[0m "
echo -e ""
echo -e "\033[92mWait in  3 sec..\033[0m"
sleep 3
menu
}

######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
#username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
#certifacate=$(((d1 - d2) / 86400))
clear
######################################
# // GETTINGS SYSTEM
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[92;1mON${NC}"
else
   status_ssh="\033[91;1mOFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[92;1mON${NC}"
else
    status_ws_epro="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[92;1mON${NC}"
else
   status_haproxy="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[92;1mON${NC}"
else
   status_xray="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[92;1mON${NC}"
else
   status_nginx="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="\033[92;1mGOOD${NC}"
else
   status_dropbear="\033[91;1mCRAZY${NC} "
fi

# Count total Account vmess
vme_total=$(grep -E "^### " "/etc/xray/config.json" | sed -E 's/^### ([^ ]+).*/\1/' | awk '!seen[$0]++')
VME=$(echo "$vme_total" | wc -l)


# Count total Account vless
vle_total=$(grep -E "^#& " "/etc/xray/config.json" | sed -E 's/^#& ([^ ]+).*/\1/' | awk '!seen[$0]++')
VLE=$(echo "$vle_total" | wc -l)


# Count total Account trojan
tro_total=$(grep -E "^#! " "/etc/xray/config.json" | sed -E 's/^#! ([^ ]+).*/\1/' | awk '!seen[$0]++')
TRO=$(echo "$tro_total" | wc -l)


# Count total Account shadowsocks
ssr_total=$(grep -E "^#!# " "/etc/xray/config.json" | sed -E 's/^#!# ([^ ]+).*/\1/' | awk '!seen[$0]++')
SSR=$(echo "$ssr_total" | wc -l)


# Count total Account noobzvpns
nob_total=$(grep -E "^#nob# " "/etc/noobzvpns/.noobzvpns" | sed -E 's/^#nob# ([^ ]+).*/\1/' | awk '!seen[$0]++')
NOB=$(echo "$nob_total" | wc -l)


# Count total Account ssh openvpn
ssh_total=$(grep -E "^#ssh# " "/etc/ssh/.ssh.db" | sed -E 's/^#ssh# ([^ ]+).*/\1/' | awk '!seen[$0]++')
SSH=$(echo "$ssh_total" | wc -l)



# // LUNATIC TUNNELING | LT PROJECT
# // WHATSAPP : 085955333616
# // TELEGRAM : LunaticTunnel
clear


clear
# // color format 38
CC='\e[38;5;14m'  # 
LO='\e[38;5;162m' # PURPLE HACKER
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[93;1m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
# // color fromat 5 
BlueCyan='\e[5;36m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
Xark='\e[0m'

GR="\e[92;1m"


function Banner_Libev() {
clear
  echo -e "\e[93;1m ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐${Xark} "
  echo -e "${GR}           FEATURES LIBEV             ${Xark} "
  echo -e "\e[93;1m └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘${Xark} "
}



function BR1() {
  echo -e "\e[93;1m ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐${Xark} "
}

function BR2() {
  echo -e "\e[93;1m └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘${Xark} "
}


function Menu_Features() {
  Banner_Libev
  BR1
  echo -e "\e[93;1m │${GR}[01]•\e[97;1m RUNNING SERVICE  "
  echo -e "\e[93;1m │${GR}[02]•\e[97;1m RESTART SERVICE  "
  echo -e "\e[93;1m │${GR}[03]•\e[97;1m AUTOREBOOT VPS  "
  echo -e "\e[93;1m │${GR}[04]•\e[97;1m MONITOR VPS INF  "
  echo -e "\e[93;1m │${GR}[05]•\e[97;1m SPEEDTEST VPS  "
  echo -e "\e[93;1m │${GR}[06]•\e[97;1m DELETE AKUN XP   "
  echo -e "\e[93;1m │${GR}[07]•\e[97;1m CHANGE BANNER   "
  echo -e "\e[93;1m │${GR}[08]•\e[97;1m CHANGE DOMAIN  "
  echo -e "\e[93;1m │${GR}[09]•\e[97;1m FIXX HAPROXY  "
  echo -e "\e[93;1m │${GR}[10]•\e[97;1m FIXX NGINX  "
  echo -e "\e[93;1m │${GR}[11]•\e[97;1m AUTO POINTING  "
  echo -e "\e[93;1m │${GR}[12]•\e[97;1m INSTAL FIX UDP   "
  echo -e "\e[93;1m │${GR}[13]•\e[97;1m BACKUP BOT VIA    "
  echo -e "\e[93;1m │${GR}[14]•\e[97;1m CLEAR ALL CACHE  "
  echo -e "\e[93;1m │${GR}[15]•\e[97;1m CLEAR ALL LOGS  "
  echo -e "\e[93;1m │${GR}[16]•\e[97;1m CLEAR LOGS FILE  "
  echo -e "\e[93;1m │${GR}[17]•\e[97;1m CHECK BANDWIDTH   "
  echo -e "\e[93;1m │${GR}[18]•\e[97;1m SCRIPT INFORMATION    "
  echo -e "\e[93;1m │${GR}[19]•\e[97;1m GANTI TAMPILAN MENU  "
  echo -e "\e[93;1m │${GR}[20]•\e[97;1m ENCRYPT & DECRYPT  "
  echo -e "\e[93;1m │${BK}[xx]•\e[0;31m EXIT ${Xark}    "
  BR2
  echo -e ""
read -p "  Just Input 1-20 or xx :  " Ltt
case $Ltt in
1) clear ; run ;;
2) clear ; reset ;;
3) clear ; autoreboot ;;
4) clear ; gotop ;;
5) clear ; speedtest ;;
6) clear ; xp ;;
7) clear ; nano /etc/banner.txt ;;
8) clear ; change-domain ;;
9) clear ; fixhap ;;
10) clear ; fixcert ;;
11) clear ; cf ;;
12) clear ; UDEPE ;;
13) clear ; m-bkp ;;
14) clear ; clearcache ;;
15) clear ; clearlog ;;
16) clear ; delet-cache-file ;;
17) clear ; vnstat ;;
18) clear ; neo ;;
19) clear ; m-tme ;;
20) clear ; ENCSSL ;;
*) menu ;;
esac
}


# // Call Function
# Banner_Libev
# Menu_Features
# Select_Menu



green='\033[0;32m'
r="\e[91;1m"
RED="\e[91;1m"
Blu_Cy="\e[5;36m"
# // color format 38
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

function Lt_System() {
clear
echo -e "   \e[93;1m──────────────────────────────────────${Suffix}"
echo -e "   \e[92;1m   .::::.${Suffix}\e[92;1m     RISWANVPN     .::::.${Suffix}"
echo -e "   \e[93;1m──────────────────────────────────────${Suffix}"

echo -e "       \e[93;1m┌───────────────────────────┐${Suffix}"
echo -e "       \e[93;1m│${BK} SYS OS :${Suffix} \e[0;36m$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')${Suffix}"
echo -e "       \e[93;1m│${BK} RAM :${Suffix} \e[0;36m$(free -m | awk 'NR==2 {print $2}') MB/$(free -m | awk 'NR==2 {print $3}') MB${Suffix}"
echo -e "       \e[93;1m│${BK} UP :${Suffix} \e[0;36m$(uptime -p | cut -d " " -f 2-10000)${Suffix}"
echo -e "       \e[93;1m│${BK} CORE :${Suffix} \e[0;36m$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")${Suffix}"
echo -e "       \e[93;1m│${BK} ISP :${Suffix} \e[0;36m$(cat /etc/xray/isp)${Suffix}"
echo -e "       \e[93;1m│${BK} CITY :${Suffix} \e[0;36m$(cat /etc/xray/city)${Suffix}"
echo -e "       \e[93;1m│${BK} IP :${Suffix} \e[0;36m$(curl -s ipv4.icanhazip.com)${Suffix}"
echo -e "       \e[93;1m│${BK} DOMAIN :${Suffix} \e[0;36m$(cat /etc/xray/domain)${Suffix}"
echo -e "       \e[93;1m└───────────────────────────┘${Suffix}"
}


function Status_Service() {
echo -e "  \e[93;1m┌──────────────────────────────────────┐${Suffix}"
echo -e "  \e[93;1m│${Suffix} SSH-WS :${Suffix} $status_ssh \e[93;1m│${Suffix} XRAY :${Suffix} $status_xray \e[93;1m│${Suffix} NGINX :${Suffix} $status_nginx \e[93;1m│${Suffix}"
echo -e "  \e[93;1m└──────────────────────────────────────┘${Suffix}"
echo -e "     \e[93;1m┌────────────────────────────────┐${Suffix}"
echo -e "     \e[93;1m│${Suffix} \e[92;1mID :${Suffix}${Blu_Cy} $(cat /usr/bin/user)${Suffix}"
echo -e "     \e[93;1m│${Suffix} \e[92;1mExp.sc :${Suffix} ${Blu_Cy}$(((d1 - d2) / 86400)) Day.Turn${Suffix}"
echo -e "     \e[93;1m└────────────────────────────────┘${Suffix}"
}


function Details_Account() {
echo -e "     \e[97;1m      SSH: $SSH NOB: $NOB  VME: $VME ${Suffix}"
echo -e "     \e[97;1m  VLESS: $VLE TROJAN: $TRO SHADWSK: $SSR ${Suffix}"
}


function Menu_Display() {
echo -e "  \e[93;1m┌──────────────────────────────────────┐${Suffix}"
echo -e "  \e[93;1m│${Suffix}\e[92;1m 1.${Suffix}\e[0;36mSSH OVPN MANAGER${Suffix}\e[92;1m  4.${Suffix}\e[0;36mTROJAN MANAGER${Suffix} \e[93;1m│${Suffix}"
echo -e "  \e[93;1m│${Suffix}\e[92;1m 2.${Suffix}\e[0;36mVMESS MANAGER${Suffix}   \e[92;1m  5.${Suffix}\e[0;36mSHDWSK MANAGER${Suffix} \e[93;1m│${Suffix}"
echo -e "  \e[93;1m│${Suffix}\e[92;1m 3.${Suffix}\e[0;36mVLESS MANAGER${Suffix}   \e[92;1m  6.${Suffix}\e[0;36mOTHER SETTINGS${Suffix} \e[93;1m│${Suffix}"
echo -e "  \e[93;1m└──────────────────────────────────────┘${Suffix}"
}

function Sc_Version() {
echo -e "             \e[97;1m Version : 7.4.7 ${Suffix}"
echo -e "          \e[95;1m━━━${Suffix}${BK}━━━${Suffix}\e[97;1m━━━${Suffix}${BK}━━━\e[92;1m━━━${Suffix}\e[93;1m━━━${Suffix}\e[94;1m━━━${Suffix}\e[96;1m━━${Suffix}"
echo -e ""
}

function Select_Display() {
read -p "      Select From Options [ 1 - 6 ] : " opt
echo -e ""
case $opt in
1 | 01)
clear
m-ssh
;;
2 | 02)
clear
m-vme
;;
3 | 03)
clear
m-vle
;;
4 | 04)
clear
m-tro
;;
5 | 05)
clear
m-ssr
;;
6 | 06)
clear
Menu_Features
;;
*)
exit
;;
esac
}


Lt_System
Status_Service
Details_Account
Menu_Display
Sc_Version
Select_Display
