#!/bin/bash
clear

function updat(){
clear
cd /usr/local/
rm -rf sbin
rm -rf /usr/bin/enc
cd
mkdir /usr/local/sbin
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m# "
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
res1() {
    wget https://raw.githubusercontent.com/Garut-SisiBukit/zexcex/main/Cdy/LT
    wget -q -O /usr/bin/enc "https://raw.githubusercontent.com/Garut-SisiBukit/zexcex/main/Enc/encrypt" ; chmod +x /usr/bin/enc
    7z e -paskykenza123 LT
    unzip LT
    chmod +x menu/*
    enc menu/*
    mv menu/* /usr/local/sbin
    rm -rf menu
    rm -rf LT
    rm -rf menu.zip
    rm -rf update.sh
    rm -rf update
    rm -rf /root/menu
    rm -rf /root/menu.zip
    rm -rf /root/update.sh
    rm -rf /root/welcome
    rm -rf /root/change-limit-xray
    rm -rf /root/change-ip-limit
    rm -rf /root/change-domain
    rm -rf /root/fixhap
    rm -rf /root/fixcert
    rm -rf /root/xtra-menu
    rm -rf /root/others
    rm -rf /root/manager
    rm -rf /root/m-ftr
    rm -rf /root/m-bkp
    rm -rf /root/m-bot
    rm -rf /root/m-ssh
    rm -rf /root/m-ssr
    rm -rf /root/m-vme
    rm -rf /root/m-vle
    rm -rf /root/m-tro
    rm -rf /root/mbot
    rm -rf /root/m-panel
    rm -rf /root/add-bot-notif
    rm -rf /root/add-ip
    rm -rf /root/add-ssh
    rm -rf /root/add-vme
    rm -rf /root/add-vle
    rm -rf /root/add-ssr    
    rm -rf /root/auto-kill
    rm -rf /root/autobackup
    rm -rf /root/autoreboot
    rm -rf /root/clearcache
    rm -rf /root/clearlog
    rm -rf /root/backup
    rm -rf /root/restore
    rm -rf /root/cek-ssh
    rm -rf /root/cek-ssr
    rm -rf /root/cek-vle
    rm -rf /root/cek-vme
    rm -rf /root/cek-tro
    rm -rf /root/member-ssh
    rm -rf /root/member-vme
    rm -rf /root/member-vle
    rm -rf /root/member-tro
    rm -rf /root/membee-ssr
    rm -rf /root/user-ssh
    rm -rf /root/user-ssr
    rm -rf /root/user-vme
    rm -rf /root/user-vle
    rm -rf /root/user-tro
    rm -rf /root/renew-ssh
    rm -rf /root/renew-ssr
    rm -rf /root/renew-vme
    rm -rf /root/renew-vle
    rm -rf /root/renew-tro
    rm -rf /root/trial-ssh
    rm -rf /root/trial-vle
    rm -rf /root/trial-ssr
    rm -rf /root/trial-vme
    rm -rf /root/trial-tro
    rm -rf /root/delexp
    rm -rf /root/xp
    rm -rf /root/member
    rm -rf /root/tendang
    rm -rf /root/speedtest
    rm -rf /root/run
    rm -rf /root/reset
    rm -rf /root/gotop
    rm -rf /root/prot
    rm -rf /root/mullog
    rm -rf /root/Lt-on-off
    rm -rf /root/limitspeed
    rm -rf /root/limitssh-ip
    rm -rf /root/lock-vmess
    rm -rf /root/lock-xray-ip
    rm -rf /root/lock
    rm -rf /root/unlock
    rm -rf /root/ganti-ip-ssh
    rm -rf /root/ganti-ip-vmess
    rm -rf /root/ganti-ip-vless
    rm -rf /root/ganti-ip-trojan
    rm -rf /root/del-ssh
    rm -rf /root/del-vme
    rm -rf /root/del-vle
    rm -rf /root/del-ssr
    rm -rf /root/del-tro
    rm -rf /root/create-bot-notif
    rm -rf /root/hapus-bot-notif
    rm -rf /root/ceklim
    rm -rf /root/about
    rm -rf /root/limit-on-off
    rm -rf /root/killtrial
    rm -rf /root/hapus-bot
    rm -rf /root/delet-cache-file
    rm -rf /root/del-bot-notif
    rm -rf /root/change-vmess-qouta
    rm -rf /root/change-vless-qouta
    rm -rf /root/change-trojan-qouta
    rm -rf /root/cf
    rm -rf /root/bot
    rm -rf /root/add-tro
    rm -rf /root/add-ip-bot
    rm -rf /root/about
    rm -rf /root/UDEPE
    rm -rf /root/Bot-Domain
    rm -rf /root/menu-noobzvpns
    rm -rf /root/welcome.bak
    rm -rf /root/scdomain
    rm -rf /root/menu-tai
    rm -rf /root/menu-mentahan
    rm -rf /root/Neo
    rm -rf /root/m-xray
    rm -rf /root/menu.bak
    rm -rf /root/del-bot-notif
    rm -rf /root/delet-cache-file
    rm -rf /root/bot
    rm -rf /root/backup
    rm -rf /root/auto-kill
    rm -rf /root/autoreboot
    rm -rf /root/auto-backup
    rm -rf /root/add-ip-bot
    rm -rf /root/ipbot
    rm -rf /root/cf
    rm -rf /root/change-trojan-qouta
    rm -rf /root/clearcache
    rm -rf /root/clearlog
    rm -rf /root/del-bot-notif
    rm -rf /root/gz13051
    rm -rf /root/gz22349
    rm -rf /root/izinsc
    rm -rf /root/Lt-on-off
    rm -rf /root/udp
}
netfilter-persistent
clear
echo -e "\e[38;5;162m┌───────────────────────────────────────────┐\033[0m "
echo -e " \e[1;97;104m               UPDATE SCRIPT         \e[0m"
echo -e "\e[38;5;162m└───────────────────────────────────────────┘\033[0m "
echo -e ""
echo -e "  \033[1;91m Ipdate version Script\033[1;37m"
fun_bar 'res1'
echo -e "\e[38;5;162m└───────────────────────────────────────────┘\033[0m "
echo -e ""
echo -e "\033[92mWait in  2 sec..\033[0m"
sleep 2
chmod +x /usr/local/sbin/fixsc
fixsc
}




function LTX() {
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
}


function Lunatix_Banner() {
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
echo -e " \e[5;36m|\e[0;35m             Sett Features    \e[0m          \e[5;36m|\e[0m"
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
}

function Menu_Features() {
Lunatix_Banner
echo -e " \e[5;36m |\e[0m \e[97;1m 1.) Info Running SerVice             \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 2.) Info Restart SerVice             \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 3.) AutoReboot Vps Server            \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 4.) Get Vps Monitoring               \e[5;36m|  \e[0m"

echo -e " \e[5;36m |\e[0m \e[97;1m 5.) Checking SpeedTest               \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 6.) Autodelete Account Expired       \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 7.) Changes Banner ssh               \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 8.) Changes Domain server            \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 9.) Fixx Haproxy Domain              \e[5;36m|  \e[0m"

echo -e " \e[5;36m |\e[0m \e[97;1m10.) Fixx Nginx Domain                \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m11.) Checking Bandwith vps            \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m12.) Themes Managers                  \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m13.) Encrypt & Decrypt                \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m14.) Update.Sc New Versions           \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m x.) Exit                             \e[5;36m|  \e[0m"
LTX
}






function Select_Menu() {
read -p "  Just Input 1-14 or x :  " Ltt
case $Ltt in
1) clear ; run ;;
2) clear ; reset ;;
3) clear ; autoreboot ;;
4) clear ; gotop ;;
5) clear ; speedtest ;;
6) clear ; xp ;;
7) clear ; nano /etc/banner.txt ;;
8) clear ; change-domain ;;
9) clear ; fixhap ;;
10) clear ; fixcert ;;
11) clear ; vnstat ;;
12) clear ; m-tme ;;
13) clear ; ENCSSL ;;
14) clear ; updat ;;
*) welcome ;;
esac
}


# // Call Function
Menu_Features
Select_Menu