#!/bin/bash
# COLOR VALIDATION
clear
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
YELL='\033[0;33m'
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
IP=$(wget -qO- icanhazip.com)
dateToday=$(date +"%Y-%m-%d")
Name=$(curl https://raw.githubusercontent.com/Garut-SisiBukit/izinsc/main/ip | grep $MYIP | awk '{print $2}')




# // color format 38
CC='\e[38;5;14m'  # 
LO='\e[38;5;162m' # PURPLE HACKER
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
# // color fromat 5 
BlueCyan='\e[5;36m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
Xark='\e[0m'


# // On / of Autobackup
clear
switch=$(grep -i "switch" /root/.bckupbot | awk '{print $2}')
clear
if [ "${switch}" == "on" ]; then
sts="\033[92;1m[ON]\033[0m"
else
sts="\033[91;1m[OF]\033[0m"
fi

# //


function BR1() {
  echo -e "${LO} ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐${Xark} "
}

function BR2() {
  echo -e "${LO} └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘${Xark} "
}




clear
BR1
echo -e "${R1}         AUTOBACKUP VPS                 \e[0m"
BR2
BR1
echo -e " ${LO}│$NC \e[97;1m[#] STS AUTOBACKUP : $sts\e[0m"
echo -e " ${LO}│$NC \e[97;1m[1] BACKUP SETIAP 1 JAM \e[0m"
echo -e " ${LO}│$NC \e[97;1m[2] BACKUP SETIAP 2 JAM \e[0m"
echo -e " ${LO}│$NC \e[97;1m[3] BACKUP SETIAP 3 JAM \e[0m"
echo -e " ${LO}│$NC \e[97;1m[4] BACKUP SETIAP 4 JAM \e[0m"
echo -e " ${LO}│$NC \e[97;1m[5] BACKUP SETIAP 5 JAM \e[0m"
echo -e " ${LO}│$NC \e[97;1m[6] BACKUP SETIAP 6 JAM \e[0m"
echo -e " ${LO}│$NC \e[91;1m[7] EXIT \e[0m"
BR2
echo ""
read -p " Just Input : " gasgas
case $gasgas in
1)
rm -rf /etc/crontab/otwbackup
rm -rf /etc/cron.d/otwbackup
sleep 2
clear
    switch=$(grep -i "switch" /root/.bckupbot | awk '{print $2}')
    if [ "${switch}" == "on" ]; then
        sed -i 's/switch on/switch off/g' /root/.bckupbot
        sed -i "/otwbackup/d" /etc/crontab
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn Off"
    else
        sed -i 's/switch off/switch on/g' /root/.bckupbot
        echo "0 * * * * root /usr/local/sbin/otwbackup" >>/etc/crontab
        echo "0 * * * * root /usr/local/sbin/otwbackup" >>/etc/cron.d/otwbackup
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
    fi
clear

        echo -e "\e[97;1m ============================= \e[0m"
        echo -e "\e[97;1m   Autobackup Setiap :\e[92;1m 1 jam\e[0m"
        echo -e "\e[97;1m ============================= \e[0m"
        echo
        read -n 1 -s -r -p "Press any key to back on Bot menu"
        m-otw
;;
2)
rm -rf /etc/crontab/otwbackup
rm -rf /etc/cron.d/otwbackup
sleep 2
clear
    switch=$(grep -i "switch" /root/.bckupbot | awk '{print $2}')
    if [ "${switch}" == "on" ]; then
        sed -i 's/switch on/switch off/g' /root/.bckupbot
        sed -i "/otwbackup/d" /etc/crontab
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn Off"
    else
        sed -i 's/switch off/switch on/g' /root/.bckupbot
        echo "0 */2 * * * root /usr/local/sbin/otwbackup" >>/etc/crontab
        echo "0 */2 * * * root /usr/local/sbin/otwbackup" >>/etc/cron.d/otwbackup
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn On"
    fi
clear

        echo -e "\e[97;1m ============================= \e[0m"
        echo -e "\e[97;1m   Autobackup Setiap :\e[92;1m 2 jam\e[0m"
        echo -e "\e[97;1m ============================= \e[0m"
        echo
        read -n 1 -s -r -p "Press any key to back on Bot menu"
        m-otw
;;
3)
rm -rf /etc/crontab/otwbackup
rm -rf /etc/cron.d/otwbackup
sleep 2
clear
    switch=$(grep -i "switch" /root/.bckupbot | awk '{print $2}')
    if [ "${switch}" == "on" ]; then
        sed -i 's/switch on/switch off/g' /root/.bckupbot
        sed -i "/otwbackup/d" /etc/crontab
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn Off"
    else
        sed -i 's/switch off/switch on/g' /root/.bckupbot
        echo "0 */3 * * * root /usr/local/sbin/otwbackup" >>/etc/crontab
        echo "0 */3 * * * root /usr/local/sbin/otwbackup" >>/etc/cron.d/otwbackup
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn On"
    fi
clear

        echo -e "\e[97;1m ============================= \e[0m"
        echo -e "\e[97;1m   Autobackup Setiap :\e[92;1m 3 jam\e[0m"
        echo -e "\e[97;1m ============================= \e[0m"
        echo
        read -n 1 -s -r -p "Press any key to back on Bot menu"
        m-otw
;;
4)
rm -rf /etc/crontab/otwbackup
rm -rf /etc/cron.d/otwbackup
sleep 2
clear
    switch=$(grep -i "switch" /root/.bckupbot | awk '{print $2}')
    if [ "${switch}" == "on" ]; then
        sed -i 's/switch on/switch off/g' /root/.bckupbot
        sed -i "/otwbackup/d" /etc/crontab
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn Off"
    else
        sed -i 's/switch off/switch on/g' /root/.bckupbot
        echo "0 */4 * * * root /usr/local/sbin/otwbackup" >>/etc/crontab
        echo "0 */4 * * * root /usr/local/sbin/otwbackup" >>/etc/cron.d/otwbackup
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn On"
    fi
clear

        echo -e "\e[97;1m ============================= \e[0m"
        echo -e "\e[97;1m   Autobackup Setiap :\e[92;1m 4 jam\e[0m"
        echo -e "\e[97;1m ============================= \e[0m"
        echo
        read -n 1 -s -r -p "Press any key to back on Bot menu"
        m-otw
;;
5)
rm -rf /etc/crontab/otwbackup
rm -rf /etc/cron.d/otwbackup
sleep 2
clear
    switch=$(grep -i "switch" /root/.bckupbot | awk '{print $2}')
    if [ "${switch}" == "on" ]; then
        sed -i 's/switch on/switch off/g' /root/.bckupbot
        sed -i "/otwbackup/d" /etc/crontab
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn Off"
    else
        sed -i 's/switch off/switch on/g' /root/.bckupbot
        echo "0 */5 * * * root /usr/local/sbin/otwbackup" >>/etc/crontab
        echo "0 */5 * * * root /usr/local/sbin/otwbackup" >>/etc/cron.d/otwbackup
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn On"
    fi
clear

        echo -e "\e[97;1m ============================= \e[0m"
        echo -e "\e[97;1m   Autobackup Setiap :\e[92;1m 5 jam\e[0m"
        echo -e "\e[97;1m ============================= \e[0m"
        echo
        read -n 1 -s -r -p "Press any key to back on Bot menu"
        m-otw
;;
6)
rm -rf /etc/crontab/otwbackup
rm -rf /etc/cron.d/otwbackup
sleep 2
clear
    switch=$(grep -i "switch" /root/.bckupbot | awk '{print $2}')
    if [ "${switch}" == "on" ]; then
        sed -i 's/switch on/switch off/g' /root/.bckupbot
        sed -i "/otwbackup/d" /etc/crontab
        service cron restart >/dev/null 2>&1
        service cron reload >/dev/null 2>&1
        echo "Turn Off"
    else
        sed -i 's/switch off/switch on/g' /root/.bckupbot
        echo "0 */6 * * * root /usr/local/sbin/otwbackup" >>/etc/crontab
        echo "0 */6 * * * root /usr/local/sbin/otwbackup" >>/etc/cron.d/otwbackup
        service cron reload >/dev/null 2>&1
        echo "Turn On"
    fi
clear

        echo -e "\e[97;1m ============================= \e[0m"
        echo -e "\e[97;1m   Autobackup Setiap :\e[92;1m 6 jam\e[0m"
        echo -e "\e[97;1m ============================= \e[0m"
        echo
        read -n 1 -s -r -p "Press any key to back on Bot menu"
        m-otw
;;
7) exit ;;
esac