#!/bin/bash
clear
# // color format 38
CC='\e[38;5;14m'  # 
LO='\e[38;5;162m' # PURPLE HACKER
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
# // color fromat 5 
BlueCyan='\e[5;36m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
Xark='\e[0m'

function LTX() {
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
}


function Lunatix_Banner() {
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
echo -e " \e[5;36m|\e[0;35m              Ssh Open Vpn    \e[0m          \e[5;36m|\e[0m"
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
}


function Menu_Features() {
Lunatix_Banner
echo -e " \e[5;36m |\e[0m \e[97;1m 1.) Create Ssh Account vpn           \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 2.) Ceeate Ssh Triall Account        \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 3.) Delete Ssh Account Vpn           \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 4.) Daftar Ssh Members               \e[5;36m|  \e[0m"

echo -e " \e[5;36m |\e[0m \e[97;1m 5.) AutoKiller ssh Account           \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 6.) Checking Ssh Mullog Account      \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 7.) Delete Ssh Account Expired       \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 8.) Change ssh Limit Ip              \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 9.) Renews Ssh Account vpn           \e[5;36m|  \e[0m"

echo -e " \e[5;36m |\e[0m \e[97;1m10.) Locked Ssh Triall Account        \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m11.) Unlocked Ssh Account Vpn         \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m12.) Change All Limit Ip              \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m13.) Monitor Ssh User Online          \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m x.) Exit                             \e[5;36m|  \e[0m"
LTX
}




Menu_Features



# // Select Display
read -p "   Just Input 1-13 or x :  " Ltt
case $Ltt in
01 | 1) clear ; add-ssh ;;
02 | 2) clear ; trial-ssh ;;
03 | 3) clear ; del-ssh ;;
04 | 4) clear ; member-ssh ;;
05 | 5) clear ; auto-kill ;;
06 | 6) clear ; mullog ;;
07 | 7) clear ; xp ;;
08 | 8) clear ; ganti-ip-ssh ;;
09 | 9) clear ; renew-ssh ;;
10) clear ; Lock ;;
11) clear ; Unlock ;;
12) clear ; Lt-on-off ;;
13) clear ; cek-ssh ;;
*) exit ;;
esac
