#!/bin/bash
clear
function LTX() {
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
}



function Lunatix_Banner() {
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
echo -e " \e[5;36m|\e[0;35m            Trojan Managers    \e[0m         \e[5;36m|\e[0m"
echo -e "\e[5;36m  ————————————————————————————————————————\e[0m"
}


function Menu_Features() {
Lunatix_Banner
echo -e " \e[5;36m |\e[0m \e[97;1m 1.) Create Trojan Account Vpn        \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 2.) Create Trojan Triall Account     \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 3.) Delete Trojan Account Vpn        \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 4.) Listed Trojan Members            \e[5;36m|  \e[0m"

echo -e " \e[5;36m |\e[0m \e[97;1m 5.) Renews Trojan Account            \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 6.) Change Trojan Limit ip           \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 7.) Monitor Trojan User Online       \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 8.) Detail Trojan Account            \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m 9.) Change Trojan Quota              \e[5;36m|  \e[0m"
echo -e " \e[5;36m |\e[0m \e[97;1m x.) Exit                             \e[5;36m|  \e[0m"
LTX
}


Menu_Features


# // Select Display
read -p "  Just Input 1-9 or xx :  " Ltt
case $Ltt in
01 | 1) clear ; add-tro ;;
02 | 2) clear ; trial-tro ;;
03 | 3) clear ; del-tro ;;
04 | 4) clear ; member-tro ;;
05 | 5) clear ; renew-tro ;;
06 | 6) clear ; ganti-ip-trojan ;;
07 | 7) clear ; cek-tro ;;
08 | 8) clear ; user-tro ;;
09 | 9) clear ; change-trojan-qouta ;;
*) exit ;;
esac
