#!/bin/bash
######################################
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
#domain=$(cat /etc/xray/domain)
#RAM=$(free -m | awk 'NR==2 {print $2}')
#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')

#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"

clear


# // Gettings Info
function upp(){
clear
cd /usr/local/
rm -rf sbin
rm -rf /usr/bin/enc
cd
mkdir /usr/local/sbin
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m# "
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
res1() {
    wget https://raw.githubusercontent.com/scriswan/v1/main/Cdy/LT
    wget -q -O /usr/bin/enc "https://raw.githubusercontent.com/scriswan/v1/main/Enc/encrypt" ; chmod +x /usr/bin/enc
    7z e -paskykenza123 LT
    unzip LT
    chmod +x menu/*
    enc menu/*
    mv menu/* /usr/local/sbin
    rm -rf menu
    rm -rf LT
    rm -rf menu.zip
    rm -rf update.sh
    rm -rf uodate
    rm -rf /root/menu
    rm -rf /root/menu.zip
    rm -rf /root/update.sh
    rm -rf /root/welcome
    rm -rf /root/change-limit-xray
    rm -rf /root/change-ip-limit
    rm -rf /root/change-domain
    rm -rf /root/fixhap
    rm -rf /root/fixcert
    rm -rf /root/xtra-menu
    rm -rf /root/others
    rm -rf /root/manager
    rm -rf /root/m-ftr
    rm -rf /root/m-bkp
    rm -rf /root/m-bot
    rm -rf /root/m-ssh
    rm -rf /root/m-ssr
    rm -rf /root/m-vme
    rm -rf /root/m-vle
    rm -rf /root/m-tro
    rm -rf /root/mbot
    rm -rf /root/m-panel
    rm -rf /root/add-bot-notif
    rm -rf /root/add-ip
    rm -rf /root/add-ssh
    rm -rf /root/add-vme
    rm -rf /root/add-vle
    rm -rf /root/add-ssr    
    rm -rf /root/auto-kill
    rm -rf /root/autobackup
    rm -rf /root/autoreboot
    rm -rf /root/clearcache
    rm -rf /root/clearlog
    rm -rf /root/backup
    rm -rf /root/restore
    rm -rf /root/cek-ssh
    rm -rf /root/cek-ssr
    rm -rf /root/cek-vle
    rm -rf /root/cek-vme
    rm -rf /root/cek-tro
    rm -rf /root/member-ssh
    rm -rf /root/member-vme
    rm -rf /root/member-vle
    rm -rf /root/member-tro
    rm -rf /root/membee-ssr
    rm -rf /root/user-ssh
    rm -rf /root/user-ssr
    rm -rf /root/user-vme
    rm -rf /root/user-vle
    rm -rf /root/user-tro
    rm -rf /root/renew-ssh
    rm -rf /root/renew-ssr
    rm -rf /root/renew-vme
    rm -rf /root/renew-vle
    rm -rf /root/renew-tro
    rm -rf /root/trial-ssh
    rm -rf /root/trial-vle
    rm -rf /root/trial-ssr
    rm -rf /root/trial-vme
    rm -rf /root/trial-tro
    rm -rf /root/delexp
    rm -rf /root/xp
    rm -rf /root/member
    rm -rf /root/tendang
    rm -rf /root/speedtest
    rm -rf /root/run
    rm -rf /root/reset
    rm -rf /root/gotop
    rm -rf /root/prot
    rm -rf /root/mullog
    rm -rf /root/Lt-on-off
    rm -rf /root/limitspeed
    rm -rf /root/limitssh-ip
    rm -rf /root/lock-vmess
    rm -rf /root/lock-xray-ip
    rm -rf /root/lock
    rm -rf /root/unlock
    rm -rf /root/ganti-ip-ssh
    rm -rf /root/ganti-ip-vmess
    rm -rf /root/ganti-ip-vless
    rm -rf /root/ganti-ip-trojan
    rm -rf /root/del-ssh
    rm -rf /root/del-vme
    rm -rf /root/del-vle
    rm -rf /root/del-ssr
    rm -rf /root/del-tro
    rm -rf /root/create-bot-notif
    rm -rf /root/hapus-bot-notif
    rm -rf /root/ceklim
    rm -rf /root/about
    rm -rf /root/limit-on-off
    rm -rf /root/killtrial
    rm -rf /root/hapus-bot
    rm -rf /root/delet-cache-file
    rm -rf /root/del-bot-notif
    rm -rf /root/change-vmess-qouta
    rm -rf /root/change-vless-qouta
    rm -rf /root/change-trojan-qouta
    rm -rf /root/cf
    rm -rf /root/bot
    rm -rf /root/add-tro
    rm -rf /root/add-ip-bot
    rm -rf /root/about
    rm -rf /root/UDEPE
    rm -rf /root/Bot-Domain
    rm -rf /root/menu-noobzvpns
}
netfilter-persistent
clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m             UPDATE SCRIPT         \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "  \033[1;91m update script service\033[1;37m"
fun_bar 'res1'
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "\033[92mWait in  3 sec..\033[0m"
sleep 3
menu
}

######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
#username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
#certifacate=$(((d1 - d2) / 86400))
clear
######################################
# // GETTINGS SYSTEM
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[92;1mON${NC}"
else
   status_ssh="\033[91;1mOFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[92;1mON${NC}"
else
    status_ws_epro="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[92;1mON${NC}"
else
   status_haproxy="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[92;1mON${NC}"
else
   status_xray="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[92;1mON${NC}"
else
   status_nginx="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="\033[92;1mGOOD${NC}"
else
   status_dropbear="\033[91;1mCRAZY${NC} "
fi

# Count total Account vmess
vme_total=$(grep -E "^### " "/etc/xray/config.json" | sed -E 's/^### ([^ ]+).*/\1/' | awk '!seen[$0]++')
VME=$(echo "$vme_total" | wc -l)


# Count total Account vless
vle_total=$(grep -E "^#& " "/etc/xray/config.json" | sed -E 's/^#& ([^ ]+).*/\1/' | awk '!seen[$0]++')
VLE=$(echo "$vle_total" | wc -l)


# Count total Account trojan
tro_total=$(grep -E "^#! " "/etc/xray/config.json" | sed -E 's/^#! ([^ ]+).*/\1/' | awk '!seen[$0]++')
TRO=$(echo "$tro_total" | wc -l)


# Count total Account shadowsocks
ssr_total=$(grep -E "^#!# " "/etc/xray/config.json" | sed -E 's/^#!# ([^ ]+).*/\1/' | awk '!seen[$0]++')
SSR=$(echo "$ssr_total" | wc -l)


# Count total Account noobzvpns
nob_total=$(grep -E "^#nob# " "/etc/noobzvpns/.noobzvpns" | sed -E 's/^#nob# ([^ ]+).*/\1/' | awk '!seen[$0]++')
NOB=$(echo "$nob_total" | wc -l)


# Count total Account ssh openvpn
ssh_total=$(grep -E "^#ssh# " "/etc/ssh/.ssh.db" | sed -E 's/^#ssh# ([^ ]+).*/\1/' | awk '!seen[$0]++')
SSH=$(echo "$ssh_total" | wc -l)



clear
function Lunatic_Banner() {
clear
echo -e "\e[5;36m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\e[5;36m│\e[0m \033[41;1;97;1m                  RISWANVPN                    \033[0m \e[5;36m│\e[0m"
echo -e "\e[5;36m└─────────────────────────────────────────────────┘\033[0m "
}

function Service_System_Operating() {
echo -e "\e[5;36m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\e[5;36m│\e[0;37m SYSTEM          :${BK} $(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')     \033[0m "
echo -e "\e[5;36m│\e[0;37m RAM             :${BK} $(free -m | awk 'NR==2 {print $2}')    \033[0m "
echo -e "\e[5;36m│\e[0;37m UPTIME          :${BK} $(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "\e[5;36m│\e[0;37m IP VPS          :${BK} $(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "\e[5;36m│\e[0;37m ISP             :${BK} $(cat /etc/xray/isp)    \033[0m "
echo -e "\e[5;36m│\e[0;37m DOMAIN          :${BK} $(cat /etc/xray/domain)    \033[0m "
echo -e "\e[5;36m└─────────────────────────────────────────────────┘\033[0m"

}



function Service_Status() {
echo -e "\e[5;36m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\e[5;36m|\033[0m\033[33m PROXY \033[0m  $status_haproxy  \e[0m|\e[33m NGINX  \e[0m $status_nginx  \e[0m|\033[33m SSHWS  \033[0m $status_ws_epro \033[0m|  $status_dropbear  \e[5;36m| \033[0m "
echo -e "\e[5;36m└─────────────────────────────────────────────────┘\033[0m "
}




function List_All_Account() {
echo -e "\e[5;36m     ┌───────────────────────────────────────┐\033[0m "
echo -e "\e[97;1m              SSH OPENVPN    :     $SSH         \033[0m " 
echo -e "\e[97;1m              VLESS XRAY     :     $VLE          \033[0m " 
echo -e "\e[97;1m              VMESS XRAY     :     $VME          \033[0m " 
echo -e "\e[97;1m              TRJAN XRAY     :     $TRO          \033[0m " 
echo -e "\e[97;1m              SSR-LIBEV      :     $SSR          \033[0m "
echo -e "\e[97;1m              NOOBZVPNS      :     $NOB          \033[0m "
echo -e "\e[5;36m     └───────────────────────────────────────┘\033[0m "
}



function Details_Clients_Name() {
echo -e "\e[5;36m   ┌───────────────────────────────────────────┐\033[0m "
echo -e "\e[5;36m   │\e[97;1m   VERSION      : 4.4.4.4 AJ.    \033[0m "
echo -e "\e[5;36m   │\e[96;1m   CLIENTS      : \033[0m\033[91;1m $(cat /usr/bin/user)      \033[0m "
echo -e "\e[5;36m   │\e[91;1m   Expiry       : \033[0m\033[91;1m $(((d1 - d2) / 86400)) Day \033[0m "
echo -e "\e[5;36m   └───────────────────────────────────────────┘\033[0m "
}



function Acces_Use_Command() {
echo -e "\e[5;36m ————————————————————————————————————————————————— \033[0m "
echo -e "\e[5;36m             acces use\033[0m \033[93;1m☞\033[0m \033[92;1mmenu\033[0m \e[5;36mcommand \033[0m " 
echo -e "\e[5;36m ————————————————————————————————————————————————— \033[0m "
}



Lunatic_Banner
Service_System_Operating
Service_Status
List_All_Account
Details_Clients_Name
Acces_Use_Command
